#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.
#
# The library expects a person at stdin. When input closes (EOF) it stops and
# says what was already written rather than treating silence as a value.
# Values land in ENV_FILE as one KEY=VALUE line each, byte-for-byte, unquoted.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

# RED is part of the palette for stage authors below the marker; the linter
# cannot see that use.
# shellcheck disable=SC2034
if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# write_env rebuilds ENV_FILE in a temp file beside it, which holds every value
# captured so far. Ctrl-C or an error between writing it and removing it would
# leave that file where .gitignore does not cover it, so its removal is owed on
# every exit, and an interrupt re-raises itself once the file is gone.
_WRITE_ENV_TMP=""
_write_env_cleanup() { [[ -n "$_WRITE_ENV_TMP" ]] && rm -f "$_WRITE_ENV_TMP"; _WRITE_ENV_TMP=""; }
trap '_write_env_cleanup' EXIT
trap '_write_env_cleanup; trap - INT; kill -INT $$' INT
trap '_write_env_cleanup; trap - TERM; kill -TERM $$' TERM

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# _valid_key KEY succeeds when KEY is a portable variable name. Anything else
# is an author error: it is named on stderr and the caller stops.
_valid_key() {
  [[ "$1" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] && return 0
  printf 'invalid environment variable name: %s\n' "$1" >&2
  return 1
}

# _input_closed WHAT: stdin closed while a prompt was waiting. Nobody is
# answering, so nothing is guessed: report what already landed and stop.
_input_closed() {
  local written="nothing"
  (( ${#WRITTEN_ENV[@]} )) && written="${WRITTEN_ENV[*]}"
  printf '\n  input closed while waiting for %s; stopping. Written so far: %s\n' \
    "$1" "$written" >&2
  exit 1
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || _input_closed "Enter"
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || _input_closed "a reply to: $1"
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any: the text after the
# first "=" of the last matching line.
_existing() {
  _valid_key "$1" || exit 1
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# _read_value KEY "Prompt" [-s] does the work of ask and ask_secret; -s hides
# the typing. Enter keeps the value already in ENV_FILE, and with none there
# it asks before accepting an empty value, so an empty result is always
# deliberate. Closed input stops the script. A pasted CRLF loses its CR.
_read_value() {
  local key="$1" prompt="$2" hidden="${3:-}" current input
  _valid_key "$key" || exit 1
  current=$(_existing "$key" || true)
  while :; do
    if [[ -n "$current" ]]; then
      printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
      printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    if [[ -n "$hidden" ]]; then
      read -rs input || _input_closed "$key"
      printf '\n'
    else
      read -r input || _input_closed "$key"
    fi
    input="${input%$'\r'}"
    [[ -n "$input" ]] && break
    if [[ -n "$current" ]]; then
      input="$current"
      note "kept current value"
      break
    fi
    confirm "Leave $key empty?" && break
  done
  printf -v "$key" '%s' "$input"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() { _read_value "$1" "$2"; }

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() { _read_value "$1" "$2" -s; }

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it). The key's
# line is replaced where it stands, a later duplicate is dropped, every other
# line keeps its place, and a missing key is appended. VALUE goes in
# byte-for-byte with no quoting or escaping, so it must be a single line: one
# holding a line break is refused and nothing is written. The file is rebuilt
# in a temp file beside it and copied back into place, so a symlinked .env and
# the file's mode survive. Idempotent.
write_env() {
  local key="$1" value="$2" tmp line found=0
  _valid_key "$key" || exit 1
  case "$value" in
    *$'\n'*|*$'\r'*)
      printf 'value for %s contains a line break; .env has no portable multi-line encoding, nothing written\n' "$key" >&2
      return 1 ;;
  esac
  tmp=$(mktemp "$ENV_FILE.XXXXXX")
  _WRITE_ENV_TMP="$tmp"
  {
    if [[ -f "$ENV_FILE" ]]; then
      while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ "$line" == "$key="* ]]; then
          (( found )) && continue
          found=1
          line="$key=$value"
        fi
        printf '%s\n' "$line"
      done < "$ENV_FILE"
    fi
    (( found )) || printf '%s=%s\n' "$key" "$value"
  } > "$tmp"
  cat "$tmp" > "$ENV_FILE"
  rm -f "$tmp"
  _WRITE_ENV_TMP=""
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated. An
# empty VALUE is never pushed: it would blank a live secret.
set_secret() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    SKIPPED+=("GitHub secret $name (empty value, not pushed)")
    warn "skipped GitHub secret $name: empty value, not pushed"
    return 0
  fi
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret). An
# empty VALUE is never pushed.
set_var() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    SKIPPED+=("GitHub variable $name (empty value, not pushed)")
    warn "skipped GitHub variable $name: empty value, not pushed"
    return 0
  fi
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=1

banner "Stripe setup"

# ── Example stage: replace with your real steps ───────────────────────────
stage "Stripe: API keys"
say "We'll grab your Stripe test keys and store them for local dev + CI."
open_url "https://dashboard.stripe.com/test/apikeys"
step "On the API keys page, copy the Publishable key (starts pk_test_)."
ask STRIPE_PUBLISHABLE_KEY "Paste the publishable key:"
step "Click 'Reveal test key' on the Secret key row, then copy it."
ask_secret STRIPE_SECRET_KEY "Paste the secret key:"
write_env STRIPE_PUBLISHABLE_KEY "$STRIPE_PUBLISHABLE_KEY"
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
set_secret STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"   # CI needs this one
# ──────────────────────────────────────────────────────────────────────────

finish
